version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "festival-du-jeu"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=festival-du-jeu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data